apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    k8s-app: global-server
  name: global-server
  selfLink: /api/v1/namespaces/default/services/global-server
spec:
  ports:
  - name: tcp-5006-5005-wfbsq
    port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    k8s-app: global-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
