apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: global-server
  name: global-server
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/global-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: global-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: global-server
      name: global-server
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        - name: MONGODB_HOST
          value: mongodb://mongo:27017/global_server
        - name: REDIS_HOST
          value: redis
        - name: WAIT_HOSTS
          value: mongo:27017
        image: ripbullnetworks/global-server:latest
        imagePullPolicy: Always
        name: global-server
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    k8s-app: global-server
  name: global-server
  selfLink: /api/v1/namespaces/default/services/global-server
spec:
  ports:
  - name: tcp-5006-5005-wfbsq
    port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    k8s-app: global-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
